repository:  
  name:  Learning-CPlusPlus-By-Reading-PPP2E
  description:  Documentation of my experiences learning to program in C++ by reading Bjarne Stroustrup's 'Programming: Principles and Practice Using C++,' Second Edition.  
